# Generated by Django 3.2.13 on 2022-05-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_alter_basket_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
