# Generated by Django 3.2.13 on 2022-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0004_alter_basket_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена продукт(а/ов)'),
        ),
    ]
