# Generated by Django 3.2.13 on 2022-05-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0005_basket_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products_price',
        ),
    ]
