# Generated by Django 3.2.13 on 2022-05-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0007_basket_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='cost',
        ),
    ]
