# Generated by Django 3.2.13 on 2022-04-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='имя категории')),
                ('description', models.TextField(blank=True, max_length=140, verbose_name='описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='товар')),
                ('description', models.TextField(blank=True, max_length=140, verbose_name='описание товара')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='изображение товара')),
                ('price',
                 models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена за ед. товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество ед. товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.category',
                                               verbose_name='категория товара')),
            ],
        ),
    ]
