# Generated by Django 3.2.13 on 2022-05-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_shopuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar',
        ),
    ]
