# Generated by Django 3.2.13 on 2022-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_shopuserprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Female')], max_length=1, verbose_name='пол'),
        ),
    ]
